- name: Ejecutar Snyk para buscar vulnerabilidades
      uses: snyk/actions/node@master  # Usamos el core de Snyk que detecta cualquier lenguaje automáticamente
      continue-on-error: true 
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
