- name: Ejecutar Snyk para buscar vulnerabilidades en Java
      uses: snyk/actions/maven@master
      continue-on-error: true 
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --all-projects
