name: CI/CD Pipeline con Monitoreo y Logging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    - name: Validar sintaxis de Docker Compose
      run: docker compose config

    - name: Construir imagenes del Microservicio
      run: docker compose build

    - name: Levantar Entorno Simulado
      run: docker compose up -d
